// Realistic Tactical Seed Data matching FieldLink Specs
import { 
  Asset, 
  Personnel, 
  RollCallRecord, 
  ChecklistExecution, 
  Incident, 
  DeviceMetadata 
} from '../types/tactical';
import { offlineStorage, STORES } from './offlineStorageService';

export const DEFAULT_DEVICE: DeviceMetadata = {
  deviceId: 'device-a17',
  deviceName: 'A-17 / NORTH NODE',
  operatorName: 'Lina Okafor',
  role: 'Field Lead',
  nodeType: 'North Node',
  status: 'online',
  batteryLevel: 94,
  isTrusted: true,
  lastSeen: Date.now(),
  vectorClock: { 'device-a17': 4, 'device-b04': 2 },
};

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'asset-mk204',
    customId: 'MK-204',
    name: 'Trauma response kit',
    category: 'Medical',
    condition: 'Good',
    status: 'Deployed',
    assignment: 'South sector',
    sector: 'Sector-4B',
    serialNumber: 'SN-TRK-9921',
    notes: 'Equipped with hemostatic dressings and tourniquets. Assigned to Combat Medic.',
    updatedAt: Date.now() - 1000 * 60 * 35,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  },
  {
    id: 'asset-sat402',
    customId: 'SAT-402',
    name: 'Tactical Satellite Transceiver',
    category: 'Comms',
    condition: 'Operational',
    status: 'Available',
    assignment: 'Base Alpha',
    sector: 'Command HQ',
    serialNumber: 'SN-SAT-8802',
    notes: 'High-gain Iridium link. Firmware 4.2. Tested OK.',
    updatedAt: Date.now() - 1000 * 60 * 90,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  },
  {
    id: 'asset-drn09',
    customId: 'DRN-09',
    name: 'Recon Quadcopter Drone',
    category: 'Mobility',
    condition: 'Good',
    status: 'Available',
    assignment: 'Drone Team',
    sector: 'North Ridge',
    serialNumber: 'SN-UAV-4410',
    notes: 'Thermal optics camera payload attached. 2 spare batteries.',
    updatedAt: Date.now() - 1000 * 60 * 120,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  },
  {
    id: 'asset-gen12',
    customId: 'GEN-12',
    name: 'Solar Power Bank 2000W',
    category: 'Power',
    condition: 'Degraded',
    status: 'Deployed',
    assignment: 'Medical Post',
    sector: 'South sector',
    serialNumber: 'SN-PWR-2001',
    notes: 'Cell 3 charging efficiency dropped by 20%. Needs technician check.',
    updatedAt: Date.now() - 1000 * 60 * 180,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  },
  {
    id: 'asset-rad88',
    customId: 'RAD-88',
    name: 'Handheld VHF/UHF Radio',
    category: 'Comms',
    condition: 'Operational',
    status: 'Deployed',
    assignment: 'Patrol Alpha',
    sector: 'Sector-2',
    serialNumber: 'SN-RAD-0088',
    notes: 'Set to tactical frequency channel 6. Battery 85%.',
    updatedAt: Date.now() - 1000 * 60 * 240,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  },
  {
    id: 'asset-nvg10',
    customId: 'NVG-10',
    name: 'Gen-3 Night Vision Goggles',
    category: 'Tactical Gear',
    condition: 'Good',
    status: 'Available',
    assignment: 'Armoury',
    sector: 'Base Alpha',
    serialNumber: 'SN-NVG-3011',
    notes: 'Auto-gated phosphor tube. Helmet mount bracket included.',
    updatedAt: Date.now() - 1000 * 60 * 300,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  }
];

export const INITIAL_PERSONNEL: Personnel[] = [
  {
    id: 'pers-01',
    callsign: 'Viper-1',
    name: 'Lina Okafor',
    rank: 'Captain',
    unit: '1st Tactical Recon',
    role: 'Team lead',
    bloodType: 'O+',
    status: 'Active',
    currentSector: 'North Node',
    equipmentCount: 3,
    lastRollCallStatus: 'Present',
    updatedAt: Date.now() - 1000 * 60 * 45,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  },
  {
    id: 'pers-02',
    callsign: 'Ghost-4',
    name: 'Marcus Vance',
    rank: 'Sergeant',
    unit: 'Alpha Fireteam',
    role: 'Scout Operator',
    bloodType: 'A+',
    status: 'Deployed',
    currentSector: 'South sector',
    equipmentCount: 4,
    lastRollCallStatus: 'Present',
    updatedAt: Date.now() - 1000 * 60 * 60,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  },
  {
    id: 'pers-03',
    callsign: 'Lifeline',
    name: 'Elena Rostova',
    rank: 'Lieutenant',
    unit: 'Medical Corps',
    role: 'Combat Medic',
    bloodType: 'B-',
    status: 'Deployed',
    currentSector: 'Medical Post',
    equipmentCount: 5,
    lastRollCallStatus: 'Present',
    updatedAt: Date.now() - 1000 * 60 * 80,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  },
  {
    id: 'pers-04',
    callsign: 'Solder',
    name: 'Tariq Chen',
    rank: 'Specialist',
    unit: 'Signal Group',
    role: 'Comms Specialist',
    bloodType: 'AB+',
    status: 'Active',
    currentSector: 'Base Alpha',
    equipmentCount: 2,
    lastRollCallStatus: 'Present',
    updatedAt: Date.now() - 1000 * 60 * 100,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  },
  {
    id: 'pers-05',
    callsign: 'Anvil',
    name: 'David Kim',
    rank: 'Corporal',
    unit: 'Logistics Lead',
    role: 'Supply Master',
    bloodType: 'O-',
    status: 'Active',
    currentSector: 'Base Alpha',
    equipmentCount: 1,
    lastRollCallStatus: 'Present',
    updatedAt: Date.now() - 1000 * 60 * 150,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  },
  {
    id: 'pers-06',
    callsign: 'Echo-7',
    name: 'Kofi Mensah',
    rank: 'Specialist',
    unit: 'Bravo Patrol',
    role: 'Rifleman',
    bloodType: 'A-',
    status: 'Deployed',
    currentSector: 'Sector-4B',
    equipmentCount: 2,
    lastRollCallStatus: 'Absent',
    updatedAt: Date.now() - 1000 * 60 * 200,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced',
  }
];

export const INITIAL_ROLL_CALL: RollCallRecord = {
  id: 'rc-2026-0912-01',
  title: 'Alpha Sector Morning Roll Call',
  sector: 'North Operational Sector',
  startedAt: Date.now() - 1000 * 60 * 30,
  completedAt: Date.now() - 1000 * 60 * 10,
  operatorName: 'Lina Okafor',
  deviceId: 'device-a17',
  status: 'Completed',
  entries: {
    'pers-01': { personnelId: 'pers-01', personnelName: 'Lina Okafor', status: 'Present', timestamp: Date.now() - 1000 * 60 * 28 },
    'pers-02': { personnelId: 'pers-02', personnelName: 'Marcus Vance', status: 'Present', timestamp: Date.now() - 1000 * 60 * 25 },
    'pers-03': { personnelId: 'pers-03', personnelName: 'Elena Rostova', status: 'Present', timestamp: Date.now() - 1000 * 60 * 22 },
    'pers-04': { personnelId: 'pers-04', personnelName: 'Tariq Chen', status: 'Present', timestamp: Date.now() - 1000 * 60 * 20 },
    'pers-05': { personnelId: 'pers-05', personnelName: 'David Kim', status: 'Present', timestamp: Date.now() - 1000 * 60 * 18 },
    'pers-06': { personnelId: 'pers-06', personnelName: 'Kofi Mensah', status: 'Absent', timestamp: Date.now() - 1000 * 60 * 15, notes: 'Patrol radio delay' },
  },
  summary: {
    total: 20,
    present: 18,
    absent: 1,
    missing: 0,
    injured: 1,
    other: 0,
  },
  updatedAt: Date.now() - 1000 * 60 * 10,
  updatedByDeviceId: 'device-a17',
  version: 1,
  lamportClock: 1,
  syncStatus: 'synced',
};

export const INITIAL_CHECKLISTS: ChecklistExecution[] = [
  {
    id: 'chk-01',
    title: 'Comms & navigation check',
    category: 'Equipment Inspection',
    status: 'Completed',
    progress: { completed: 8, total: 8 },
    items: [
      { id: 'c1-1', label: 'VHF/UHF Handheld radio frequency calibration', completed: true },
      { id: 'c1-2', label: 'Primary GPS lock acquired (minimum 6 satellites)', completed: true },
      { id: 'c1-3', label: 'Mesh transceiver signal ping verified', completed: true },
      { id: 'c1-4', label: 'Satellite link battery level > 80%', completed: true },
      { id: 'c1-5', label: 'Emergency beacon distress key checked', completed: true },
      { id: 'c1-6', label: 'Encryption key rollover synchronized', completed: true },
      { id: 'c1-7', label: 'Backup compass and analog topo charts packed', completed: true },
      { id: 'c1-8', label: 'Audio headset & PTT switch tactile response verified', completed: true }
    ],
    updatedAt: Date.now() - 1000 * 60 * 40,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced'
  },
  {
    id: 'chk-02',
    title: 'Deployment preparation',
    category: 'Deployment Prep',
    status: 'In Progress',
    progress: { completed: 11, total: 14 },
    items: [
      { id: 'c2-1', label: 'Field rations and hydration bladders sealed (72h)', completed: true },
      { id: 'c2-2', label: 'Level III-A Ballistic plates inspected', completed: true },
      { id: 'c2-3', label: 'First aid individual blowout kits stocked', completed: true },
      { id: 'c2-4', label: 'Night vision tubes focus and battery verified', completed: true },
      { id: 'c2-5', label: 'Vehicle fluid levels and tire pressure checked', completed: true },
      { id: 'c2-6', label: 'Power bank cells charged to 100%', completed: true },
      { id: 'c2-7', label: 'Weather & barometric telemetry updated', completed: true },
      { id: 'c2-8', label: 'Squad radio channel assignment confirmed', completed: true },
      { id: 'c2-9', label: 'Designated rendezvous coordinates marked', completed: true },
      { id: 'c2-10', label: 'Hazardous terrain route briefed to all leads', completed: true },
      { id: 'c2-11', label: 'Asset assignment receipts confirmed in FieldLink', completed: true },
      { id: 'c2-12', label: 'Backup mesh node relay positioned', completed: false },
      { id: 'c2-13', label: 'Secondary drone thermal camera test flight', completed: false },
      { id: 'c2-14', label: 'Final roll call sign-off by Command', completed: false }
    ],
    updatedAt: Date.now() - 1000 * 60 * 20,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced'
  },
  {
    id: 'chk-03',
    title: 'Emergency response protocol',
    category: 'Emergency Response',
    status: 'In Progress',
    progress: { completed: 3, total: 12 },
    items: [
      { id: 'c3-1', label: 'Casualty triage priority protocol activated', completed: true },
      { id: 'c3-2', label: 'Emergency frequency beacon broadcasting', completed: true },
      { id: 'c3-3', label: 'Secondary evacuation LZ coordinates verified', completed: true },
      { id: 'c3-4', label: 'Medical oxygen and tourniquet kit deployed', completed: false },
      { id: 'c3-5', label: 'Perimeter defense lock and sector alert raised', completed: false },
      { id: 'c3-6', label: 'Tactical mesh node emergency delta broadcasted', completed: false },
      { id: 'c3-7', label: 'Asset accountability lock initiated', completed: false },
      { id: 'c3-8', label: 'Air extraction signal flares staged', completed: false },
      { id: 'c3-9', label: 'Critical data snapshot exported to local vault', completed: false },
      { id: 'c3-10', label: 'Hostile/hazard vector triangulated', completed: false },
      { id: 'c3-11', label: 'Squad leader handoff confirmed', completed: false },
      { id: 'c3-12', label: 'Final incident debrief logged', completed: false }
    ],
    updatedAt: Date.now() - 1000 * 60 * 15,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced'
  }
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-01',
    incidentCode: 'INC-881',
    type: 'Medical Emergency',
    severity: 'Critical',
    description: 'Specialist Kofi Mensah sustained leg fracture and severe heat dehydration during ridge reconnaissance.',
    locationSector: 'Sector-4B Ridge',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    reporter: 'Elena Rostova (Combat Medic)',
    relatedPersonnelIds: ['pers-06', 'pers-03'],
    relatedAssetIds: ['asset-mk204'],
    status: 'Monitoring',
    reportedAt: Date.now() - 1000 * 60 * 50,
    updatedAt: Date.now() - 1000 * 60 * 25,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced'
  },
  {
    id: 'inc-02',
    incidentCode: 'INC-882',
    type: 'Equipment Failure',
    severity: 'Medium',
    description: 'Solar Power Bank GEN-12 output dropped below threshold during medical refrigeration cycle.',
    locationSector: 'South sector Medical Post',
    coordinates: { lat: 34.0545, lng: -118.2411 },
    reporter: 'David Kim',
    relatedPersonnelIds: ['pers-05'],
    relatedAssetIds: ['asset-gen12'],
    status: 'Open',
    reportedAt: Date.now() - 1000 * 60 * 95,
    updatedAt: Date.now() - 1000 * 60 * 95,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced'
  },
  {
    id: 'inc-03',
    incidentCode: 'INC-883',
    type: 'Comms Blackout',
    severity: 'High',
    description: 'Intermittent RF jamming detected on standard tactical VHF channel 6 in north sector gorge.',
    locationSector: 'North Ridge Gorge',
    coordinates: { lat: 34.0588, lng: -118.2499 },
    reporter: 'Tariq Chen',
    relatedPersonnelIds: ['pers-04'],
    relatedAssetIds: ['asset-rad88', 'asset-sat402'],
    status: 'Open',
    reportedAt: Date.now() - 1000 * 60 * 140,
    updatedAt: Date.now() - 1000 * 60 * 140,
    updatedByDeviceId: 'device-a17',
    version: 1,
    lamportClock: 1,
    syncStatus: 'synced'
  }
];

export async function seedDatabaseIfEmpty(): Promise<void> {
  const existingAssets = await offlineStorage.getAll<Asset>(STORES.ASSETS);
  if (existingAssets.length === 0) {
    await offlineStorage.bulkPut(STORES.ASSETS, INITIAL_ASSETS, true);
    await offlineStorage.bulkPut(STORES.PERSONNEL, INITIAL_PERSONNEL, true);
    await offlineStorage.put(STORES.ROLL_CALLS, INITIAL_ROLL_CALL, true);
    await offlineStorage.bulkPut(STORES.CHECKLISTS, INITIAL_CHECKLISTS, true);
    await offlineStorage.bulkPut(STORES.INCIDENTS, INITIAL_INCIDENTS, true);
    await offlineStorage.put(STORES.DEVICE_METADATA, DEFAULT_DEVICE, true);
  }
}
